### ISSUE TITLE
server side code

### ISSUE THREAD

**Issue by ivanlewis** [jmichas/SignalRF#3]
Can you please post the server side code?
and how to invoke simple send("") method?

**Comment by jmichas** [comment]
Hi Ivan,

I dont currently have any time to put together the server side code for an example. But, you should be able to use the SignalR documentation to get you started. The server side code is the same for any of the client side libraries. You can maybe follow the javascript client docs if you are just getting started, or the c# client. My library sort of blends concepts from both of those implementations.

Thanks,
Jason

**Comment by ivanlewis** [comment]
ok thanx.
